# Site settings
title: Documentation
description: Latest docs

# Theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Math support
math: mathjax  # enables MathJax v3 automatically

# Markdown
markdown: kramdown
kramdown:
  math_engine: nil   # disable default math rendering; we use MathJax
  input: GFM

# Permalinks
permalink: pretty