title: Documentation
description: Latest docs

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Math support
markdown: kramdown
kramdown:
    math_engine: katex

# Permalinks
permalink: pretty