title: Documentation
description: Latest docs

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

# Math support
markdown: kramdown
kramdown:
  input: GFM
  math_engine: katex
  parse_block_html: true

# Permalinks
permalink: pretty